version: '3.13'

services:
  # Тестовая база данных
  test_db:
    image: postgres:17-alpine
    container_name: store_test_db
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db

    healthcheck:
      # Указываем конкретные значения, которые прописаны в environment выше
      test: [ "CMD-SHELL", "pg_isready -U test_user -d test_db" ]
      interval: 10s # Для тестов лучше сделать интервал почаще
      timeout: 5s
      retries: 5

  # Само приложение
  test_app:
    build: .
    container_name: test_fastapi_app
    env_file: .env.test
    depends_on:
      test_db:
        condition: service_healthy
    volumes:
      - .:/app # Монтируем код для autoreload
    command: pytest -v -s
