"""Initial commit

Revision ID: aae5f7e22ff1
Revises: d657c48fb296
Create Date: 2026-04-12 22:20:34.071022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae5f7e22ff1'
down_revision: Union[str, Sequence[str], None] = 'd657c48fb296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_products',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_products_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cart_products_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', 'product_id', name=op.f('pk_cart_products'))
    )
    op.drop_table('carts_products')
    op.create_unique_constraint(op.f('uq_carts_user_id'), 'carts', ['user_id'])
    op.drop_constraint(op.f('fk_group_users_group_id_groups'), 'group_users', type_='foreignkey')
    op.drop_constraint(op.f('fk_group_users_user_id_users'), 'group_users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_group_users_user_id_users'), 'group_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_group_users_group_id_groups'), 'group_users', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    op.drop_constraint(op.f('fk_group_users_group_id_groups'), 'group_users', type_='foreignkey')
    op.drop_constraint(op.f('fk_group_users_user_id_users'), 'group_users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_group_users_user_id_users'), 'group_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_group_users_group_id_groups'), 'group_users', 'groups', ['group_id'], ['id'])
    op.drop_constraint(op.f('uq_carts_user_id'), 'carts', type_='unique')
    op.create_table('carts_products',
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_carts_products_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_carts_products_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', 'product_id', name=op.f('pk_carts_products'))
    )
    op.drop_table('cart_products')
    # ### end Alembic commands ###
