"""Initial commit

Revision ID: b1e49e94b745
Revises: 9697ad25a280
Create Date: 2026-04-16 19:49:43.488449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e49e94b745'
down_revision: Union[str, Sequence[str], None] = '9697ad25a280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('group_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_permissions_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_group_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_id', name=op.f('pk_group_permissions'))
    )
    op.drop_column('group_users', 'id')
    op.create_unique_constraint(op.f('uq_groups_name'), 'groups', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_groups_name'), 'groups', type_='unique')
    op.add_column('group_users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_table('group_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
